const

{ ------ US English ------- }
  LowButtonName: Array[1..88] of PChar = ('--Esc','1','2','3','4','5','6','7','8','9',
                                          '0','-','=','«','--Tab','q','w','e','r','t',
                                          'y','u','i','o','p','[',']','--Enter','--Ctrl','a',
                                          's','d','f','g','h','j','k','l',';','''','`',
                                          '--LShift Down','\','z','x','c','v','b','n','m',',',
                                          '.','/','--RShift Down','--Gray*','--Alt',' ',
                                          '--CapsLock','--F1','--F2','--F3','--F4','--F5',
                                          '--F6','--F7','--F8','--F9','--F10',
                                          '--NumLock','--ScrollLock','--Home','--Up',
                                          '--PgUp','--Gray-','--Left','--*5*','--Right',
                                          '--Gray+','--End','--Down','--PgDown','--Ins',
                                          '--Del','--LShift Up','--RShift Up',
                                          '--Unknown','--F11','--F12');
  HiButtonName: Array[1..88] of PChar = ('--Esc','!','@','#','$','%','^','&','*','(',
                                         ')','_','+',' <Bksp> ','--Tab','Q','W','E','R','T',
                                         'Y','U','I','O','P','{','}','--Enter','--Ctrl','A',
                                         'S','D','F','G','H','J','K','L',':','"','~',
                                         '--LShift Down','|','Z','X','C','V','B','N','M','<',
                                         '>','?','--RShift Down','--Gray*','--Alt',' ',
                                         '--CapsLock','--F1','--F2','--F3','--F4','--F5',
                                         '--F6','--F7','--F8','--F9','--F10',
                                         '--NumLock','--ScrollLock','--Home','--Up',
                                         '--PgUp','--Gray-','--Left','--*5*','--Right',
                                         '--Gray+','--End','--Down','--PgDown','--Ins',
                                         '--Del','--LShift Up','--RShift Up',
                                         '--Unknown','--F11','--F12');

{ ------ Italian (standard) ------- }

 ItalianLowButtonName: Array[1..88] of PChar = ('--Esc','1','2','3','4','5','6','7','8','9',
                                          '0','''','ì','--BkSp','--Tab','q','w','e','r','t',
                                          'y','u','i','o','p','è','+','--Enter','--Ctrl','a',
                                          's','d','f','g','h','j','k','l','ò','à','ù',
                                          '--LShift Down','<','z','x','c','v','b','n','m',',',
                                          '.','-','--RShift Down','--Gray*','--Alt','--Space',
                                          '--CapsLock','--F1','--F2','--F3','--F4','--F5',
                                          '--F6','--F7','--F8','--F9','--F10',
                                          '--NumLock','--ScrollLock','--Home','--Up',
                                          '--PgUp','--Gray-','--Left','--*5*','--Right',
                                          '--Gray+','--End','--Down','--PgDown','--Ins',
                                          '--Del','--LShift Up','--RShift Up',
                                          '--Unknown','--F11','--F12');
 ItalianHiButtonName: Array[1..88] of PChar = ('--Esc','!','"','£','$','%','&','/','(',')',
                                         '=','?','^','--BkSp','--Tab','Q','W','E','R','T',
                                         'Y','U','I','O','P','é','*','--Enter','--Ctrl','A',
                                         'S','D','F','G','H','J','K','L','ç','','ƒ',
                                         '--LShift Down','>','Z','X','C','V','B','N','M',';',
                                         ':','_','--RShift Down','--Gray*','--Alt','--Space',
                                         '--CapsLock','--F1','--F2','--F3','--F4','--F5',
                                         '--F6','--F7','--F8','--F9','--F10',
                                         '--NumLock','--ScrollLock','--Home','--Up',
                                         '--PgUp','--Gray-','--Left','--*5*','--Right',
                                         '--Gray+','--End','--Down','--PgDown','--Ins',
                                         '--Del','--LShift Up','--RShift Up',
                                         '--Unknown','--F11','--F12');

{ ------ Russian ------- }

  RussianLowButtonName: Array[1..88] of PChar = ('--Esc','1','2','3','4','5','6','7','8','9',
                                                 '0','-','=','--BkSp','--Tab','é','ö','ó','ê','å',
                                                 'í','ã','ø','ù','ç','õ','ú','--Enter','--Ctrl','ô',
                                                 'û','â','à','ï','ð','î','ë','ä','æ','ý','¸',
                                                 '--LShift Down','\','ÿ','÷','ñ','ì','è','ò','ü','á',
                                                 'þ','.','--RShift Down','--Gray*','--Alt','--Space',
                                                 '--CapsLock','--F1','--F2','--F3','--F4','--F5',
                                                 '--F6','--F7','--F8','--F9','--F10',
                                                 '--NumLock','--ScrollLock','--Home','--Up',
                                                 '--PgUp','--Gray-','--Left','--*5*','--Right',
                                                 '--Gray+','--End','--Down','--PgDown','--Ins',
                                                 '--Del','--LShift Up','--RShift Up',
                                                 '--Unknown','--F11','--F12');

  RussianHiButtonName: Array[1..88] of PChar = ('--Esc','!','@','#','$','%','^','&','*','(',
                                                ')','_','+','--BkSp','--Tab','É','Ö','Ó','Ê','Å',
                                                'Í','Ã','Ø','Ù','Ç','{','}','--Enter','--Ctrl','Ô',
                                                'Û','Â','À','Ï','Ð','Î','Ë','Ä','Æ','Ý','¨',
                                                '--LShift Down','|','ß','×','Ñ','Ì','È','Ò','Ü','Á',
                                                'Þ',',','--RShift Down','--Gray*','--Alt','--Space',
                                                '--CapsLock','--F1','--F2','--F3','--F4','--F5',
                                                '--F6','--F7','--F8','--F9','--F10',
                                                '--NumLock','--ScrollLock','--Home','--Up',
                                                '--PgUp','--Gray-','--Left','--*5*','--Right',
                                                '--Gray+','--End','--Down','--PgDown','--Ins',
                                                '--Del','--LShift Up','--RShift Up',
                                                '--Unknown','--F11','--F12');

{ ------ Ukrainian ------- }
